DELETE FROM scan_records;
DELETE FROM people;

INSERT INTO people (person_id, display_name, role, secret_id, secret_path_token) VALUES
  ('mentor-anindya-putri-utami-s-m-m-m', 'Anindya Putri Utami, S.M., M.M.', 'mentor', 'mentor-secret-anindya-putri-utami-s-m-m-m', '7j896r34xe3y'),
  ('mentor-bd-mariza-mustika-d-s-tr-keb-m-tr-keb', 'Bd. Mariza Mustika D, S.Tr.Keb., M.Tr.Keb', 'mentor', 'mentor-secret-bd-mariza-mustika-d-s-tr-keb-m-tr-keb', 'tibk4uhnvvfh'),
  ('mentor-bondan-eko-suratno-m-hum', 'Bondan Eko Suratno, M.Hum', 'mentor', 'mentor-secret-bondan-eko-suratno-m-hum', '0r2aj56to52q'),
  ('mentor-daffa-restu-fadhillah-s-kom', 'Daffa Restu Fadhillah, S.Kom', 'mentor', 'mentor-secret-daffa-restu-fadhillah-s-kom', 'dphquxhopg6u'),
  ('mentor-dendi-krisna-nugraha-m-sc-ph-d', 'Dendi Krisna Nugraha, M.Sc., Ph.D.', 'mentor', 'mentor-secret-dendi-krisna-nugraha-m-sc-ph-d', 'zcccq4ekctzm'),
  ('mentor-dian-respati-ayu-s-si-m-biomed', 'Dian Respati Ayu, S.Si., M.Biomed', 'mentor', 'mentor-secret-dian-respati-ayu-s-si-m-biomed', 'rodxna8fda4r'),
  ('mentor-dina-haida-shofwa-a-md-keb', 'Dina Haida Shofwa, A.Md.Keb.', 'mentor', 'mentor-secret-dina-haida-shofwa-a-md-keb', 'os76g82sex8k'),
  ('mentor-dr-ir-agus-f-abdillah-mba-ermap', 'Dr. Ir. Agus F. Abdillah, MBA, ERMAP', 'mentor', 'mentor-secret-dr-ir-agus-f-abdillah-mba-ermap', 'uunfierj9lmr'),
  ('mentor-eva-fachria-s-e-m-s-m', 'Eva Fachria, S.E., M.S.M.', 'mentor', 'mentor-secret-eva-fachria-s-e-m-s-m', 'znm7ma09269q'),
  ('mentor-mohammad-ariq-nazar-s-si-m-biomed', 'Mohammad Ariq Nazar, S.Si, M.Biomed', 'mentor', 'mentor-secret-mohammad-ariq-nazar-s-si-m-biomed', 'wk19xijm3dqq'),
  ('mentor-mr-adam', 'Mr Adam', 'mentor', 'mentor-secret-mr-adam', 'm58gajvc5djr'),
  ('mentor-mr-dendi', 'Mr Dendi', 'mentor', 'mentor-secret-mr-dendi', 'ndvvyfm8h6yq'),
  ('mentor-mr-faheem', 'Mr Faheem', 'mentor', 'mentor-secret-mr-faheem', 'hu0t15p89e9q'),
  ('mentor-mr-faris', 'Mr Faris', 'mentor', 'mentor-secret-mr-faris', 'v4iwny3jmmet'),
  ('mentor-mr-naufal-sebastian-anggoro', 'Mr Naufal Sebastian Anggoro', 'mentor', 'mentor-secret-mr-naufal-sebastian-anggoro', 'n101rq5kfm50'),
  ('mentor-ms-endah', 'Ms Endah', 'mentor', 'mentor-secret-ms-endah', 'e2xfw5o4mm9x'),
  ('mentor-ms-nina', 'Ms Nina', 'mentor', 'mentor-secret-ms-nina', 'ikb7ztlw3u70'),
  ('mentor-ms-waheni', 'Ms Waheni', 'mentor', 'mentor-secret-ms-waheni', 'b6dhcl8ocrdc'),
  ('mentor-najmi-rizki-khairani-s-sos-m-i-kom', 'Najmi Rizki Khairani, S.Sos., M.I.Kom', 'mentor', 'mentor-secret-najmi-rizki-khairani-s-sos-m-i-kom', 'ihz6y2f7w4nn'),
  ('mentor-naufal-sebastian-s-h-m-h', 'Naufal Sebastian, S.H.,M.H.', 'mentor', 'mentor-secret-naufal-sebastian-s-h-m-h', 'xitzhuk8duyb'),
  ('mentor-nurul-hidayah-s-si-m-biotech', 'Nurul Hidayah S.Si, M.Biotech', 'mentor', 'mentor-secret-nurul-hidayah-s-si-m-biotech', 'uwdwgsbvs4v8'),
  ('mentor-panji-agung-pedekso-s-hum', 'Panji Agung Pedekso, S.Hum', 'mentor', 'mentor-secret-panji-agung-pedekso-s-hum', '1d83leiqo3dk'),
  ('mentor-prof-yayuk', 'Prof Yayuk', 'mentor', 'mentor-secret-prof-yayuk', 'w0jt5m186p83'),
  ('mentor-rifky-ariya-pratama-s-kom', 'Rifky Ariya Pratama, S.Kom.', 'mentor', 'mentor-secret-rifky-ariya-pratama-s-kom', 'fxgruau2s5b5'),
  ('mentor-salindri-prawitasari-s-si-m-si', 'Salindri Prawitasari, S.Si, M.Si.', 'mentor', 'mentor-secret-salindri-prawitasari-s-si-m-si', 'f4lnr30vyrji'),
  ('mentor-sutinnarto-s-i-kom-m-i-kom', 'Sutinnarto, S.I.Kom., M.I.Kom', 'mentor', 'mentor-secret-sutinnarto-s-i-kom-m-i-kom', '1so9u86kb9e3'),
  ('student-alvin-syaptia-pratama-s-i-kom', 'Alvin Syaptia Pratama, S.I.Kom', 'student', 'student-secret-alvin-syaptia-pratama-s-i-kom', 'guiorvvmg0ix'),
  ('student-alya-namira-ikfinasulkha-s-ip', 'Alya Namira Ikfinasulkha, S.IP.', 'student', 'student-secret-alya-namira-ikfinasulkha-s-ip', 'wrluk3z2sfxa'),
  ('student-alya-pramesty-s-si', 'Alya Pramesty, S.Si', 'student', 'student-secret-alya-pramesty-s-si', 'i6nkiw5ght2h'),
  ('student-bdn-sri-mularsih-s-sit-m-kes', 'Bdn. Sri Mularsih, S.SiT, M.Kes', 'student', 'student-secret-bdn-sri-mularsih-s-sit-m-kes', 'o9yjqttaxqrc'),
  ('student-bdn-titik-kurniawati-s-sit-m-kes-m-keb', 'Bdn. Titik Kurniawati, S.SiT, M.Kes, M.Keb', 'student', 'student-secret-bdn-titik-kurniawati-s-sit-m-kes-m-keb', '6f6dx491tgl8'),
  ('student-bela-pristiandani-s-ak', 'Bela Pristiandani, S.Ak', 'student', 'student-secret-bela-pristiandani-s-ak', '76ahck788ftn'),
  ('student-claudea-winandyaz-r-s-pd-m-pd', 'Claudea Winandyaz R, S.Pd, M.Pd.', 'student', 'student-secret-claudea-winandyaz-r-s-pd-m-pd', 'o6001hbzxzb1'),
  ('student-dewi-elliana-skm-s-tr-keb-m-kes', 'Dewi Elliana, SKM, S.Tr.Keb, M.Kes', 'student', 'student-secret-dewi-elliana-skm-s-tr-keb-m-kes', 'x3ud9sg3i5iz'),
  ('student-diah-widyatun-s-s-t-m-tr-keb', 'Diah Widyatun, S.S.T., M.Tr.Keb', 'student', 'student-secret-diah-widyatun-s-s-t-m-tr-keb', 'dpm5yt5qgtmf'),
  ('student-dini-cahyani-s-si-m-biotech', 'Dini Cahyani, S.Si, M.Biotech', 'student', 'student-secret-dini-cahyani-s-si-m-biotech', 'po7p58592lit'),
  ('student-dr-erwin-s-h-m-h', 'dr. Erwin, S.H., M.H', 'student', 'student-secret-dr-erwin-s-h-m-h', '0b3t21yrms3q'),
  ('student-erna-setyaningsih-s-s-t-m-tr-keb', 'Erna Setyaningsih, S.S.T.,M.Tr.Keb', 'student', 'student-secret-erna-setyaningsih-s-s-t-m-tr-keb', 'u55073jk3xyi'),
  ('student-fauziah-novita-putri-rifai-s-si-m-biotech', 'Fauziah Novita Putri Rifai, S.Si, M.Biotech', 'student', 'student-secret-fauziah-novita-putri-rifai-s-si-m-biotech', 'fjz1blwsdlqp'),
  ('student-firda-rismadhani-s-m', 'Firda Rismadhani, S.M', 'student', 'student-secret-firda-rismadhani-s-m', 'ar5z2cmemj3d'),
  ('student-galih-nanda-purnama-s-ds', 'Galih Nanda Purnama , S.Ds', 'student', 'student-secret-galih-nanda-purnama-s-ds', 'w236ipo304z2'),
  ('student-labbra-pasaribu-s-m', 'Labbra Pasaribu, S.M', 'student', 'student-secret-labbra-pasaribu-s-m', '13qml1einddg'),
  ('student-lakna-tulas-un-s-sos-m-i-kom', 'Lakna Tulas''un, S.Sos, M.I.Kom', 'student', 'student-secret-lakna-tulas-un-s-sos-m-i-kom', 'igmpt7klpfgd'),
  ('student-muhamad-agung-s-s-sos-m-sos', 'Muhamad Agung S, S.Sos., M.Sos', 'student', 'student-secret-muhamad-agung-s-s-sos-m-sos', '5r20f00coacy'),
  ('student-nadya-audina-ns-s-si-m-biomed', 'Nadya Audina NS. S.Si., M.Biomed', 'student', 'student-secret-nadya-audina-ns-s-si-m-biomed', 'vf46dzevx72f'),
  ('student-putri-aryo-jelang-fitri-khothimah-s-e-m-m', 'Putri Aryo Jelang Fitri Khothimah, S.E., M.M.', 'student', 'student-secret-putri-aryo-jelang-fitri-khothimah-s-e-m-m', 'n3i67gm324cz'),
  ('student-qolbi-hanif-fadhlulloh-s-h-m-h', 'Qolbi Hanif Fadhlulloh, S.H.,M.H.', 'student', 'student-secret-qolbi-hanif-fadhlulloh-s-h-m-h', 'sm89ph4eboth'),
  ('student-rahmawati-s-a-b', 'Rahmawati, S.A.B', 'student', 'student-secret-rahmawati-s-a-b', 'vxt060xpgpci'),
  ('student-randika-shafly-fawwaz-s-m-m-m', 'Randika Shafly Fawwaz, S.M., M.M', 'student', 'student-secret-randika-shafly-fawwaz-s-m-m-m', 'zjq53ts8gz6c'),
  ('student-reni-nur-arifah-s-e-m-m', 'Reni Nur Arifah, S.E., M.M.', 'student', 'student-secret-reni-nur-arifah-s-e-m-m', 'vojggkrsf4ou'),
  ('student-ridha-azahra-s-pd', 'Ridha Azahra, S.Pd', 'student', 'student-secret-ridha-azahra-s-pd', '68csl6vlwldx'),
  ('student-rif-atul-himmah-s-sos-m-i-kom', 'Rif''atul Himmah, S.Sos. M.I.Kom.', 'student', 'student-secret-rif-atul-himmah-s-sos-m-i-kom', 'usx7tfldjyc7'),
  ('student-risky-chandra-satria-irawan-s-si-m-biomed', 'Risky Chandra Satria Irawan S.Si, M.Biomed', 'student', 'student-secret-risky-chandra-satria-irawan-s-si-m-biomed', '0ld6mp93avpp'),
  ('student-rizqitha-s-tr-keb-m-tr-keb', 'Rizqitha, S.Tr.Keb., M.Tr.Keb', 'student', 'student-secret-rizqitha-s-tr-keb-m-tr-keb', 'wb379uqi80vv'),
  ('student-rudi-hermawan-s-kom', 'Rudi Hermawan S.Kom', 'student', 'student-secret-rudi-hermawan-s-kom', 'qaecvupd642x'),
  ('student-yetty-yuliany-k-s-e-m-m', 'Yetty Yuliany K, S.E., M.M', 'student', 'student-secret-yetty-yuliany-k-s-e-m-m', 'ks7mgxadtej4'),
  ('student-zain-arfin-utama-s-h-m-h', 'Zain Arfin Utama, S.H., M.H.', 'student', 'student-secret-zain-arfin-utama-s-h-m-h', 'u3b6iwlm6k02');
